### ISSUE TITLE
No exams available for students

### ISSUE THREAD

**Issue by Michelle5757** [vinesmsuic/Online-Examination-System#1]
Hello, I've tried to use your code but it looks like I don't have exams available.. 
![image](https://user-images.githubusercontent.com/77832753/105473418-c76b7680-5ca5-11eb-92cc-48ad91501b88.png)
![image](https://user-images.githubusercontent.com/77832753/105473381-bae71e00-5ca5-11eb-9355-8b69275a09e8.png)

**Comment by vinesmsuic** [comment]
Hi, can you provide more detail?

**Comment by Michelle5757** [comment]
Hello. So basically, I've added a test as a new teacher. Just 2-3 questions for a test. After this, I've created a student account, after login on the landing page I saw that I have some new tests, and when I clicked on the Take Exam tab I saw ,,Seems that there is no exam now."

**Comment by vinesmsuic** [comment]
I just tested it on my local machine. In the first picture "Student take exam page" the reason you see there is no exam is probably due to your time isn't in the Exam Time (i.e. Your time is neither in 11:24 - 11:30 or 11:26 - 11:27).

Try to create an exam that is close to your time and then test it again.

**Comment by Michelle5757** [comment]
Hello, it is in the right time, I've sent you an email, we can check via TeamViewer if you want

**Comment by Michelle5757** [comment]
Here's the proof:
![image](https://user-images.githubusercontent.com/77832753/105482011-7b71ff00-5cb0-11eb-8c4e-aca813a8f8ab.png)

**Comment by vinesmsuic** [comment]
I see. Then it is probably the timezone problem.

Try replace all occurrence of `date_default_timezone_set("Asia/Hong_Kong")` in those PHP codes with the timezone you locate.

I was supposed to code it to auto-detect the client timezone. Sorry, my bad.
Like I mentioned in the README, this repo is going to do a code refactor.

**Comment by Michelle5757** [comment]
It was the timezone problem, thanks! No problem, it can happen sometimes. OK, I'm waiting for the refactoring process.
